const en_dictionary = {
    Dictionary: {
        About: 'About',
        AboutDescription: 'This is a SPA generated by the Mavention SPA Yeoman generator.',
        AppSubTitle: 'SPA',
        AppTitle: 'Mavention',
        Dutch: 'Dutch',
        English: 'English',
        Home: 'Home',
        HomeDescription: 'Welcome to this SPA!',
        Languages: 'Languages',
        Logout: 'Sign out',
        MyAccount: 'My account',
        User: 'User',
        UserDescription: 'OAuth Data:',
    }
};

export default en_dictionary;
